# Generated by Django 6.0.1 on 2026-02-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='population',
        ),
        migrations.AlterField(
            model_name='country',
            name='area',
            field=models.TextField(),
        ),
    ]
