# Generated by Django 6.0.1 on 2026-02-06 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country_app', '0002_remove_country_population_alter_country_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='area',
            new_name='Description',
        ),
    ]
