# Generated by Django 6.0.1 on 2026-02-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_app', '0003_rename_area_country_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='photo',
            field=models.ImageField(default='', upload_to='countries/'),
            preserve_default=False,
        ),
    ]
